version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    container_name: social_network
    volumes:
      - .:/social_network
    ports:
      - "8080:8080"